# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Summon.create(summontype: "Character", weapon: "Ramulus", event: "", icon: "", character: "Anila", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Purifying Thunderbolt", event: "", icon: "", character: "Shiva", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Delta Quartz", event: "", icon: "", character: "Beatrix (Themed)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Lohengrin", event: "", icon: "", character: "Percival", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ixaba", event: "", icon: "", character: "Sturm", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tanzanite Blade", event: "", icon: "", character: "Therese (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Scarlet Crest Axe", event: "", icon: "", character: "Yuel", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sacred Lance", event: "", icon: "", character: "Athena", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Mobius Strip", event: "", icon: "", character: "Clarisse", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Brahma Gauntlet", event: "", icon: "", character: "Ghandagoza", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Draco Claw", event: "", icon: "", character: "Grea", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Arjunan Bow", event: "", icon: "", character: "Ilsa (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sunflower Wand", event: "", icon: "", character: "Io (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Feendrache Pennant", event: "", icon: "", character: "Lancelot and Vane", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Illusion Scepter", event: "", icon: "", character: "Magisa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Roseate Aetherial Bow", event: "", icon: "", character: "Metera", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Antwerp", event: "", icon: "", character: "Percival (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Two by Four", event: "", icon: "", character: "Tsubasa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Thunder Dirk Jove", event: "", icon: "", character: "Agielba", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Magma Gauntlet", event: "", icon: "", character: "Aliza", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Benedia", event: "", icon: "", character: "Rackam (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Blushing Blossom Pin", event: "", icon: "", character: "Societte (Fire)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Starblaze Rings", event: "", icon: "", character: "Zahlhamelina", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Brionac", event: "", icon: "", character: "Zeta", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Forbidden Inferno", event: "", icon: "", character: "Anthuria", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Snack Pole", event: "", icon: "", character: "Danua (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Luin", event: "", icon: "", character: "Heles", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Delta Apex", event: "", icon: "", character: "Beatrix (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Nature's Mystery", event: "", icon: "", character: "Dante (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Glass Bow", event: "", icon: "", character: "Sutera (Fire)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Akhu", event: "", icon: "", character: "Abby", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Kaister Knuckles", event: "", icon: "", character: "Alec", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ember Blade", event: "", icon: "", character: "Carren", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Dolphin", event: "", icon: "", character: "Cucouroux", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Rope Knuckles", event: "", icon: "", character: "Ghandagoza (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wandering Blade", event: "", icon: "", character: "Lucius (Fire)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Time-Tested Iron", event: "", icon: "", character: "Rosine (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Crimson Talons", event: "", icon: "", character: "Sen", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Scarlet Oath", event: "", icon: "", character: "Teena (Valentine)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Soulbound Dirk", event: "", icon: "", character: "Teena", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tanzanite Sword Mikoh", event: "", icon: "", character: "Therese", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Arson Link", event: "", icon: "", character: "Blazing Teacher Elmott", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Deathly Arson", event: "", icon: "", character: "Elmott (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Red-Hot Noodles", event: "", icon: "", character: "Ippatsu (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Signal Flare", event: "", icon: "", character: "Karva (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Fire Piece", event: "", icon: "", character: "Mary (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Massive Axe", event: "", icon: "", character: "Ryan (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Witch's Broom", event: "", icon: "", character: "Anna (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Custom Arquebus", event: "", icon: "", character: "Jessica (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Cup and Saucer", event: "", icon: "", character: "Dorothy", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Arson", event: "", icon: "", character: "Elmott", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Chain Knuckles", event: "", icon: "", character: "Ezecrain", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Forest Hermit Staff", event: "", icon: "", character: "Dante", rarity: "R")
Summon.create(summontype: "Character", weapon: "Derringer", event: "", icon: "", character: "Barawa", rarity: "R")
Summon.create(summontype: "Character", weapon: "Cold Noodles", event: "", icon: "", character: "Ippatsu (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Little Scarlet", event: "", icon: "", character: "Drusilla", rarity: "R")
Summon.create(summontype: "Character", weapon: "Flame Bow", event: "", icon: "", character: "Flesselles", rarity: "R")
Summon.create(summontype: "Character", weapon: "Chopsticks", event: "", icon: "", character: "Ippatsu", rarity: "R")
Summon.create(summontype: "Character", weapon: "Flame Bolt", event: "", icon: "", character: "Karva", rarity: "R")
Summon.create(summontype: "Character", weapon: "Vintage Flat Iron", event: "", icon: "", character: "Rosine", rarity: "R")
Summon.create(summontype: "Character", weapon: "Feather Wand", event: "", icon: "", character: "Anna", rarity: "R")
Summon.create(summontype: "Character", weapon: "Torch", event: "", icon: "", character: "Camieux", rarity: "R")
Summon.create(summontype: "Character", weapon: "Firecracker", event: "", icon: "", character: "Mary (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Soldier Axe", event: "", icon: "", character: "Ryan", rarity: "R")
Summon.create(summontype: "Character", weapon: "Iron Pliers", event: "", icon: "", character: "Viceroy", rarity: "R")
Summon.create(summontype: "Character", weapon: "Cursed Flame Candelabra", event: "", icon: "", character: "Anna (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Ghillie Fork", event: "", icon: "", character: "Elmelaura", rarity: "R")
Summon.create(summontype: "Character", weapon: "Broken Bottle", event: "", icon: "", character: "Lamretta (R)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Petronel", event: "", icon: "", character: "Mary", rarity: "R")

Summon.create(summontype: "Character", weapon: "Dainsleif", event: "", icon: "", character: "Altair", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Blue Sphere", event: "", icon: "", character: "Drang", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Galilei's Insight", event: "", icon: "", character: "Europa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Draco Horn", event: "", icon: "", character: "Grea (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Vlisragna", event: "", icon: "", character: "Silva", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Canisius", event: "", icon: "", character: "Vajra", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Izayoi", event: "", icon: "", character: "Yuel (Water)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gottfried", event: "", icon: "", character: "Aglovale", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Daemon's Spine", event: "", icon: "", character: "Anne", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Stardust Holly Rod", event: "", icon: "", character: "Arulumaya (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Claíomh Solais", event: "", icon: "", character: "Charlotta", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tlepilli", event: "", icon: "", character: "Diantha (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Frostbite", event: "", icon: "", character: "Izmir (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Nagelring", event: "", icon: "", character: "Izmir", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Murgleis", event: "", icon: "", character: "Katalina (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Hoarfrost Blade Persius", event: "", icon: "", character: "Lancelot", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ice Crystal Staff", event: "", icon: "", character: "Lily", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Raikiri", event: "", icon: "", character: "Narmaya (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Taisai Spirit Bow", event: "", icon: "", character: "Pholia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Montague's Oath", event: "", icon: "", character: "Romeo", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Blossom Axe", event: "", icon: "", character: "Vane (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Meteora", event: "", icon: "", character: "Yngwie", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Fudo-Kuniyuki", event: "", icon: "", character: "Yodarha (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Phantom Thief Blade", event: "", icon: "", character: "Chat Noir", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "White Hawk", event: "", icon: "", character: "Cucouroux (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Metal Hand", event: "", icon: "", character: "Lady Katapillar and Vira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Melodic Sphere", event: "", icon: "", character: "Lilele", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Froststar Staff", event: "", icon: "", character: "Macula Marius", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Scarlet Vane", event: "", icon: "", character: "Societte", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sword of Sorcery", event: "", icon: "", character: "Owen", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aquarium Harp", event: "", icon: "", character: "Ejaeli", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ripple Rapier", event: "", icon: "", character: "Katalina (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aquablade", event: "", icon: "", character: "Mina", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Epoxy Boogie Plates", event: "", icon: "", character: "Cailana (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Floaty Sword", event: "", icon: "", character: "Charlotta (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Royal Rapier", event: "", icon: "", character: "Ange", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Water Balloons", event: "", icon: "", character: "Camieux (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ice Bough Staff", event: "", icon: "", character: "Erin", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Macuahuitl", event: "", icon: "", character: "Farrah (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Quarrel", event: "", icon: "", character: "Sahli Lao", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Titanium Harpoon", event: "", icon: "", character: "Sig", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sunshade Parasol", event: "", icon: "", character: "Suframare (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Narval", event: "", icon: "", character: "Ulamnuran", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Bottle o' Blossoms", event: "", icon: "", character: "Lamretta (Water)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Summer Beach Sphere", event: "", icon: "", character: "Lilele (WSummer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ice Bow", event: "", icon: "", character: "Milleore", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Spritewood Staff", event: "", icon: "", character: "Mishra", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Colorful Crackerjack", event: "", icon: "", character: "Pengy", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Raging Halberd", event: "", icon: "", character: "Vane", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Boogie Plates", event: "", icon: "", character: "Cailana", rarity: "R")
Summon.create(summontype: "Character", weapon: "White Sword", event: "", icon: "", character: "Bridgette", rarity: "R")
Summon.create(summontype: "Character", weapon: "Tattoo Fist", event: "", icon: "", character: "Randall", rarity: "R")
Summon.create(summontype: "Character", weapon: "Silver Pole", event: "", icon: "", character: "Joel", rarity: "R")
Summon.create(summontype: "Character", weapon: "Snowman Rod", event: "", icon: "", character: "Suframare", rarity: "R")
Summon.create(summontype: "Character", weapon: "Student Notebook", event: "", icon: "", character: "Alistair", rarity: "R")
Summon.create(summontype: "Character", weapon: "Night Horn", event: "", icon: "", character: "Deliford", rarity: "R")
Summon.create(summontype: "Character", weapon: "Shrimp Lure", event: "", icon: "", character: "Yodarha", rarity: "R")
Summon.create(summontype: "Character", weapon: "Self Defender", event: "", icon: "", character: "Richard", rarity: "R")

Summon.create(summontype: "Character", weapon: "Mirror-Blade Shard", event: "", icon: "", character: "Alexiel", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ancient Bandages", event: "", icon: "", character: "Ayer", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ichigo Hitofuri", event: "", icon: "", character: "Cain (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Neko Punch Pro", event: "", icon: "", character: "Dante and Freiheit", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ascalon", event: "", icon: "", character: "Siegfried", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Greatsword Andalius", event: "", icon: "", character: "Aletheia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gargantua", event: "", icon: "", character: "Arulumaya", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ouroboros", event: "", icon: "", character: "Cagliostro", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Thyrsus", event: "", icon: "", character: "De La Fille (Earth)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Stratomizer", event: "", icon: "", character: "Eustace", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Soul Eater", event: "", icon: "", character: "Hallessena", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gallinarius", event: "", icon: "", character: "Mahira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Medusiana Staff", event: "", icon: "", character: "Medusa (Valentine)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Thorny Rose", event: "", icon: "", character: "Rosetta (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sandcastle Song-Lume", event: "", icon: "", character: "Sara", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Wurtzite Scythe", event: "", icon: "", character: "Vaseraga (Earth)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Arsene", event: "", icon: "", character: "Catherine", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Snow Mobius Strip", event: "", icon: "", character: "Clarisse (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "AK-4A", event: "", icon: "", character: "Eugen (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Nightmare Mobilizer", event: "", icon: "", character: "Eustance (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gandiva", event: "", icon: "", character: "Ilsa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Mettle", event: "", icon: "", character: "Nemone", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gae Derg", event: "", icon: "", character: "Razia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Wyrmtiger Claw", event: "", icon: "", character: "Soriz (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Bella Aeterna", event: "", icon: "", character: "Yggdrasil", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Euripedes", event: "", icon: "", character: "Medusa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Vassago", event: "", icon: "", character: "Melleau", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Deep Desire", event: "", icon: "", character: "Vira (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tughril", event: "", icon: "", character: "NezaHualpilli (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tropical Punch", event: "", icon: "", character: "Ayer", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ram-Dao", event: "", icon: "", character: "Gayne", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Shrike's Beak", event: "", icon: "", character: "Jamil", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Flower Crown", event: "", icon: "", character: "Jasmine (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Gold-Plated Fremel", event: "", icon: "", character: "Almeida (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Prideful Sword", event: "", icon: "", character: "Beatrix (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Great Hammer", event: "", icon: "", character: "Galadar (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Grand Edge", event: "", icon: "", character: "Herja (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Serpentine Longspear", event: "", icon: "", character: "Leona", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Heavy-Duty Pumpkins", event: "", icon: "", character: "Mimlemel and Pun-Kin (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Divine Spear", event: "", icon: "", character: "Razia (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Giant Fork", event: "", icon: "", character: "Redluck", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ripple Harp", event: "", icon: "", character: "Sara (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Impact Knuckles", event: "", icon: "", character: "Soriz", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Macho Hunter Weapon", event: "", icon: "", character: "The Lowain Bros", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Fremel Hammer", event: "", icon: "", character: "Almeida", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Demitasse", event: "", icon: "", character: "Catherine (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Silver Rings", event: "", icon: "", character: "J.J. (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Handy Arquebus", event: "", icon: "", character: "Jessica", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tyrian Tiger Blade", event: "", icon: "", character: "Jin (Themed)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Obsidian Bow", event: "", icon: "", character: "Jin (Event)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Metal Glove", event: "", icon: "", character: "Ladiva", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Zhonpeli", event: "", icon: "", character: "Lamretta", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Mythril Tonfa", event: "", icon: "", character: "Vanzza (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sudarshana", event: "", icon: "", character: "Carmelina (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Golden Mop", event: "", icon: "", character: "Claudia", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Desert Arms", event: "", icon: "", character: "Egen (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Dreadflayer", event: "", icon: "", character: "Laguna", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Flare Glaive", event: "", icon: "", character: "Mariah", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Holy Harp", event: "", icon: "", character: "Rackam (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sword of Lisblanc", event: "", icon: "", character: "Farrah (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sandcastle Spear", event: "", icon: "", character: "Sara (Event)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Iron Guard", event: "", icon: "", character: "Balurga", rarity: "R")
Summon.create(summontype: "Character", weapon: "Heavy Metal Comb", event: "", icon: "", character: "La Coiffe", rarity: "R")
Summon.create(summontype: "Character", weapon: "Rubia Rod", event: "", icon: "", character: "Camieux (Earth)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Draph Hammer", event: "", icon: "", character: "Galadar", rarity: "R")
Summon.create(summontype: "Character", weapon: "Xiphos", event: "", icon: "", character: "Volenna", rarity: "R")
Summon.create(summontype: "Character", weapon: "Sawed-Off Shotgun", event: "", icon: "", character: "Garma", rarity: "R")
Summon.create(summontype: "Character", weapon: "Two-Handed Sword", event: "", icon: "", character: "Herja", rarity: "R")
Summon.create(summontype: "Character", weapon: "Oven Mitts", event: "", icon: "", character: "Nene", rarity: "R")
Summon.create(summontype: "Character", weapon: "Stone Pole", event: "", icon: "", character: "Norcel", rarity: "R")
Summon.create(summontype: "Character", weapon: "Tonfa", event: "", icon: "", character: "Vanzza", rarity: "R")
Summon.create(summontype: "Character", weapon: "Fire Sword", event: "", icon: "", character: "Farrah", rarity: "R")
Summon.create(summontype: "Character", weapon: "Taiaha", event: "", icon: "", character: "Jasmine", rarity: "R")
Summon.create(summontype: "Character", weapon: "Wooden Dagger", event: "", icon: "", character: "Walder (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Tree Wand", event: "", icon: "", character: "Walder (Holiday)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Main Gauche", event: "", icon: "", character: "Walder", rarity: "R")

Summon.create(summontype: "Character", weapon: "Dormius", event: "", icon: "", character: "Andira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Vortex of the Void", event: "", icon: "", character: "Grimnir", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Deirdre's Symbol", event: "", icon: "", character: "Heles (Wind)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Orleans Standard", event: "", icon: "", character: "Jeanne d'Arc (Themed)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Reunion", event: "", icon: "", character: "Lecia (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Returner Staff", event: "", icon: "", character: "Yurius", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Windflash", event: "", icon: "", character: "Gawain", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Wing of the Pure", event: "", icon: "", character: "Korwa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Heiliges Schwert", event: "", icon: "", character: "Lancelot (Wind)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Far Away", event: "", icon: "", character: "Lennah", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Split End", event: "", icon: "", character: "Melissabelle", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Aetherial Bow", event: "", icon: "", character: "Metera", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Pilum", event: "", icon: "", character: "Nezahualpilli", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Love Eternal", event: "", icon: "", character: "Rosetta (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Deirdre's Claws", event: "", icon: "", character: "Scathacha", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Cythara Anglica", event: "", icon: "", character: "Selfira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Galactic Impact", event: "", icon: "", character: "Sen (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sinensis", event: "", icon: "", character: "Siegfried (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Another Sky", event: "", icon: "", character: "Vira (Wind)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Crimson Sapphire", event: "", icon: "", character: "Yuel (Themed)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Yyrkoon", event: "", icon: "", character: "Yuisis", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Cords of Heaven Lillah", event: "", icon: "", character: "Arriet", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Heroic Bow", event: "", icon: "", character: "Feena", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Bell of Happy Endings", event: "", icon: "", character: "Korwa (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Heaven's Cloud", event: "", icon: "", character: "Petra (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tiamat Bolt Prime", event: "", icon: "", character: "Tiamat", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Turpin Spear", event: "", icon: "", character: "Carmelina", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Kilij", event: "", icon: "", character: "Juri", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Unsigned Blade", event: "", icon: "", character: "Mirin", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Zanbatto", event: "", icon: "", character: "Sevilbarra", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Festive Frying Pan", event: "", icon: "", character: "Yaia (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tilvung", event: "", icon: "", character: "Helnar", rarity: "SR")
Summon.create(summontype: "Character", weapon: "White Flag", event: "", icon: "", character: "Mimlemel and Stumpeye", rarity: "SR")
Summon.create(summontype: "Character", weapon: "White Talons", event: "", icon: "", character: "Sen (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Holy Axe", event: "", icon: "", character: "Sevastien", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sutera's Bow", event: "", icon: "", character: "Sutera", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Summer Souteyrand", event: "", icon: "", character: "Yuisis (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Balisarde", event: "", icon: "", character: "Arthur and Mordred", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Seaside Memory", event: "", icon: "", character: "Chloe (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sahdow Scepter", event: "", icon: "", character: "Goblin Mage", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Merciless Chastening", event: "", icon: "", character: "Hazen (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Silver Fan", event: "", icon: "", character: "Karteira (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Stravaria", event: "", icon: "", character: "Keehar", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tiger Fang", event: "", icon: "", character: "Mimlemel", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Standard Albion Bolt", event: "", icon: "", character: "Tyre", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Cloud Tomahawk", event: "", icon: "", character: "Eso (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Skirt Chaser", event: "", icon: "", character: "Helnar (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Priate Sword", event: "", icon: "", character: "Lecia (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Songsmith's Harp", event: "", icon: "", character: "Elta", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Jeunesse", event: "", icon: "", character: "Korwa(SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Enchanted Nail", event: "", icon: "", character: "Chloe", rarity: "R")
Summon.create(summontype: "Character", weapon: "Practice Sword", event: "", icon: "", character: "Thelonim", rarity: "R")
Summon.create(summontype: "Character", weapon: "Paper Fan", event: "", icon: "", character: "Karteira", rarity: "R")
Summon.create(summontype: "Character", weapon: "Moss Tree Staff", event: "", icon: "", character: "Petra", rarity: "R")
Summon.create(summontype: "Character", weapon: "Lightbringer", event: "", icon: "", character: "Stan", rarity: "R")
Summon.create(summontype: "Character", weapon: "Sky Tomahawk", event: "", icon: "", character: "Eso", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mythril Knuckles", event: "", icon: "", character: "Hazen", rarity: "R")
Summon.create(summontype: "Character", weapon: "Dark Sword", event: "", icon: "", character: "Leonora", rarity: "R")
Summon.create(summontype: "Character", weapon: "Light Buckler", event: "", icon: "", character: "Pavidus", rarity: "R")
Summon.create(summontype: "Character", weapon: "Old Sword", event: "", icon: "", character: "Krugne", rarity: "R")

Summon.create(summontype: "Character", weapon: "Hauteclaire", event: "", icon: "", character: "Albert", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Claidheamh Soluis", event: "", icon: "", character: "Charlotta (Light)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Fusion Mobius", event: "", icon: "", character: "Clarisse (Light)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Eden", event: "", icon: "", character: "Lucio", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Pinkie Needle", event: "", icon: "", character: "Metera (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Conifer", event: "", icon: "", character: "Naoise (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Railgun", event: "", icon: "", character: "Robomi", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Hrotti", event: "", icon: "", character: "Sereul", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Certificus", event: "", icon: "", character: "Vira (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Dragon Slayer", event: "", icon: "", character: "Amira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gothic Cutlery", event: "", icon: "", character: "Dorothy and Claudia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ethereal Lasher", event: "", icon: "", character: "Ferry (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Crystal Luin", event: "", icon: "", character: "Heles (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gambanteinn", event: "", icon: "", character: "Io (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Caladbolg", event: "", icon: "", character: "Jeanne d'Arc", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Capulet's Oath", event: "", icon: "", character: "Juliet", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Porculius", event: "", icon: "", character: "Kumbhira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Levin Shooter", event: "", icon: "", character: "Levin Sisters", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Jolly Starcracker", event: "", icon: "", character: "Mary (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Twin Helix", event: "", icon: "", character: "Rosamia (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sealed Claustrum", event: "", icon: "", character: "Sarunan", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Full Metal Recoil", event: "", icon: "", character: "Silva (Light)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Cletine", event: "", icon: "", character: "Zeta (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ruler of Fate", event: "", icon: "", character: "Zooey", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Symbol of Justice", event: "", icon: "", character: "Baotorda (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Kerykeion", event: "", icon: "", character: "De La Fille", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Diamond Edge", event: "", icon: "", character: "De La Fille (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sword on the Cob", event: "", icon: "", character: "Melissabelle (Valentine)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ocean Harp", event: "", icon: "", character: "Sophia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Jack-O'-Brand", event: "", icon: "", character: "Charlotta (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Heavy Blast Knuckles", event: "", icon: "", character: "Feather (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Lance d'Espoir", event: "", icon: "", character: "Jeanne d'Arc (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Samurai Sword", event: "", icon: "", character: "Mirin (Light)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "True Teardrop", event: "", icon: "", character: "Vermeil (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aerial Cane", event: "", icon: "", character: "Arusha", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Winter Wonderbow", event: "", icon: "", character: "Feena (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wind-Rhyme Staff", event: "", icon: "", character: "Noa", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Soothing Torch", event: "", icon: "", character: "Rosamia (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Staff of the Star Seeker", event: "", icon: "", character: "Sophia (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Arondight", event: "", icon: "", character: "Baotorda", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Crocskin Glove", event: "", icon: "", character: "Barawa (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Golden Woofer", event: "", icon: "", character: "Daetta (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sacred Codex", event: "", icon: "", character: "Johann", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Holy Glove", event: "", icon: "", character: "Ladiva (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Humming Bard", event: "", icon: "", character: "Elta (Light)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aura Whip", event: "", icon: "", character: "Ferry (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Soul Edge", event: "", icon: "", character: "Ferry", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Misanga Bracelet", event: "", icon: "", character: "J.J.", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Slingshot", event: "", icon: "", character: "Sarya", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Blue Crest", event: "", icon: "", character: "Cordelia", rarity: "R")
Summon.create(summontype: "Character", weapon: "Prism Tear", event: "", icon: "", character: "Vermeil", rarity: "R")
Summon.create(summontype: "Character", weapon: "Morning Star", event: "", icon: "", character: "Daetta", rarity: "R")
Summon.create(summontype: "Character", weapon: "Light Staff", event: "", icon: "", character: "Philosophia", rarity: "R")
Summon.create(summontype: "Character", weapon: "Blast Knuckles", event: "", icon: "", character: "Feather", rarity: "R")
Summon.create(summontype: "Character", weapon: "Thunder Rapier", event: "", icon: "", character: "Rosamia", rarity: "R")

Summon.create(summontype: "Character", weapon: "Cute Ribbon", event: "", icon: "", character: "Zooey (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Shadow Viperlance", event: "", icon: "", character: "Azazel", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Unheil", event: "", icon: "", character: "Ferry (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Disparia", event: "", icon: "", character: "Jeanne d'Arc (Dark)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Distant Requiem", event: "", icon: "", character: "Lady Grey (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Venustas", event: "", icon: "", character: "Narmaya", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Fallen Sword", event: "", icon: "", character: "Olivia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Parazonium", event: "", icon: "", character: "Orchid", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Master Key", event: "", icon: "", character: "Wulf and Renie", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gram", event: "", icon: "", character: "Beatrix", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Blutgang", event: "", icon: "", character: "Black Knight", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Silphium", event: "", icon: "", character: "Clarisse (Valentine)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ishtar", event: "", icon: "", character: "Eustace (Dark)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ukonvasara", event: "", icon: "", character: "Lady Grey", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gigante Slicer", event: "", icon: "", character: "Nicholas", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gandring", event: "", icon: "", character: "Tanya (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Azoth", event: "", icon: "", character: "Vania", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Mistilteinn", event: "", icon: "", character: "Vaseraga", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Bloody Scar", event: "", icon: "", character: "Veight", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Lyst Sin", event: "", icon: "", character: "Vira (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sunspot Spear", event: "", icon: "", character: "Zeta (Dark)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Black Ouroboros", event: "", icon: "", character: "Cagliostro (Dark)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Coco & Mimi", event: "", icon: "", character: "Cerberus", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Mikazuki", event: "", icon: "", character: "Danua (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Skyrend Spear", event: "", icon: "", character: "Forte", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ruling Pen", event: "", icon: "", character: "Lunalu (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gridarvor", event: "", icon: "", character: "Marquiares", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Rosen Maiden", event: "", icon: "", character: "Rosetta (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ouroboros Treat", event: "", icon: "", character: "Cagliostro (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Arachne", event: "", icon: "", character: "Freezie", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Summer Night Peak", event: "", icon: "", character: "Arulumaya (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Phantom Gauntlet", event: "", icon: "", character: "Feather (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Cruel Claw", event: "", icon: "", character: "Predator", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Genius Squared", event: "", icon: "", character: "Skull", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Vampire's Nail", event: "", icon: "", character: "Vania (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Cursed Cane", event: "", icon: "", character: "Will (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Puppet Knife", event: "", icon: "", character: "Danua", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Brocken Lance", event: "", icon: "", character: "Deliford (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Katzbalger", event: "", icon: "", character: "Jamil (Dark)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Voulge", event: "", icon: "", character: "Zaja", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Purity Blade", event: "", icon: "", character: "Lucius", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Silver Shotel", event: "", icon: "", character: "Randall (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Shade Knife", event: "", icon: "", character: "Tanya (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wyrm Claw", event: "", icon: "", character: "Tanya (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Dracula Harp", event: "", icon: "", character: "Ange (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Confection Cutter", event: "", icon: "", character: "Narmaya (Valentine)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Scalpel", event: "", icon: "", character: "Shao", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Hunter's Rifle", event: "", icon: "", character: "Ludmila", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Goldie", event: "", icon: "", character: "Richard (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Night Bell", event: "", icon: "", character: "Lunalu", rarity: "R")
Summon.create(summontype: "Character", weapon: "Night Air Bell", event: "", icon: "", character: "Lunalu (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Switchblade", event: "", icon: "", character: "Lowain", rarity: "R")
Summon.create(summontype: "Character", weapon: "Cleaver", event: "", icon: "", character: "Lowain (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Bronze Bell", event: "", icon: "", character: "Bakura", rarity: "R")
Summon.create(summontype: "Character", weapon: "Bloody Piercer", event: "", icon: "", character: "Tanya", rarity: "R")
Summon.create(summontype: "Character", weapon: "Zehek", event: "", icon: "", character: "Mandau", rarity: "R")
Summon.create(summontype: "Character", weapon: "The Cross", event: "", icon: "", character: "Will", rarity: "R")


Summon.create(summontype: "Character", weapon: "Fragarach", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Almace", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ilhoon", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Twisted Dagger", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Mirage Knife", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Stiletto", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Fusetto", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sword Breaker", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Trident", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Partisan", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Dragonflair Cutter", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Shura Vhara", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Vajranda", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Bullova", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Shoka", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Horseman's Hammer", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Yagrush", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Pastoral Staff", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Holy Cane", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Dragon Tail", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wheellock Axe", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Crosswind", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Snaphance", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Swallowtail", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Mauler", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Neko Punch", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Jamadhar", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Imperial Bow", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sarnga", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aves", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Elfin Bow", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Shadow Bow", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Athanasius", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Iron Tiger", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Fluorithium Blade", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sauria", event: "", icon: "", character: "None", rarity: "SR")

Summon.create(summontype: "Character", weapon: "Garnet Carbuncle", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Hellhound", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Hydra", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Vrazarek Firewyrm", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Angelie Cascade", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aquamarine Carbuncle", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wilinus Icewyrm", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Clay Golem", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Doomwork", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Golem", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Myconid", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ruination Gargoyle", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Stone Golem", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Zircon Carbuncle", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Elmenhilde Windsprite", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Elusious Windwyrm", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Griffin", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wyvern", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Opal Carbuncle", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Pixie", event: "", icon: "", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Onyx Carbuncle", event: "", icon: "", character: "None", rarity: "SR")

Summon.create(summontype: "Character", weapon: "Anelace", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Claymore", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Falchion", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Flame Rapier", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Ice Sword", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Ice Nail", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Earth Cutlass", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Fire Baselard", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Kila", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mailbreaker", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Water Kukri", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Kris", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Emerald Dagger", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Leaf Dagger", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Holy Kris", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Assassin's Dagger", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Dark Knife", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Couse", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Fire Glaive", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Flame Halberd", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Langdebeve", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Aquan Killer", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Earth Halberd", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Halberd", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Harvester", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Battle Axe", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Earth Zaghnal", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Rock Hammer", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Wind Axe", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Tabar", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Thunder Kalinga Axe", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Neckchopper", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Cane", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Ocean Rod", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Water Rod", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Feather Staff", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Emerald Cane", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Wind Rod", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Shareeravadi", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Evil Wand", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Grenade", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Matchlock", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Straight Anchor", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Ranger Pistol", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Hand Pistol", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Jezail", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Fireball", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Heated Pata", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Pata", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Fish Tooth", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Gauntlet", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Tidal Wraps", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Rock Cutter", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mythril Baghnakhs", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Whirlwind Wraps", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Composite Bow", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mythril Bow", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Longbow", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Earth Bow", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Power Bow", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "War Bow", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Wrapped Bow", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Lyre of Lamia", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Nodachi", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mythril Katana", event: "", icon: "", character: "None", rarity: "R")

Summon.create(summontype: "Character", weapon: "Minotaur", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Twilight Devil", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Venom Lancer", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Walking Torch", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Angelie", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Crusher", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Jawfish", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Purgatorian", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Rivacuda", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Slime", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Swordshark", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Bonethorn", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Crawler", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Lumacie Griffin", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mandrake", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Sleepyhead", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Belle", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Dragonflair", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Hornbird", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Rodfly", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Ghost Light", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Cave Bat", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Imp", event: "", icon: "", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Skeleton", event: "", icon: "", character: "None", rarity: "R")

Summon.create(summontype: "Character", weapon: "Agni", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Athena", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Michael", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Prometheus", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Satyr", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sethlans", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Shiva", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sylph, Flutterspirit of Purity", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Twin Elements", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Zaoshen", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Bonito", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ca Ong", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Europa", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gabriel", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Grani", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Kaguya", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Macula Marius", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Neptune", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Oceanus", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Poseidon, the Tide Father", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Snow White", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Varuna", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ankusha", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Baal", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Cybele", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gilgamesh", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Godsword Alexiel", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gorilla", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Marduk, Battlefield Reaper", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Medusa", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tezcatlipoca", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Titan", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Uriel", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Anat, for Love and War", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Demonbream", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Freyr", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Garuda", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Garula, Shining Hawk", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Grimnir", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Hamsa", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Morrigna", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Nezha", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Quetzalcoatl", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Raphael", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Rose Queen", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Setekh", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Siren", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Zephyrus", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Andramalech", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Aphrodite", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Apollo", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Grand Order", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Halluel and Malluel", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Hector", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Lucifer", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Magus, Triad of Wisdom", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Odin", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Thor", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Vortex Dragon", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Zeus", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Anubis", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Bahamut", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Cerberus, Hellhound Trifecta", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Dark Angel Olivia", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Hades", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Lich", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Nacht", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sariel", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Satan", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tsukuyomi", event: "", icon: "", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Typhon", event: "", icon: "", character: "None", rarity: "SSR")
