# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Summon.create(summontype: "Character", weapon: "Ramulus", character: "Anila", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Purifying Thunderbolt", character: "Shiva", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Delta Quartz", character: "Beatrix (Themed)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Lohengrin", character: "Percival", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ixaba", character: "Sturm", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tanzanite Blade", character: "Therese (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Scarlet Crest Axe", character: "Yuel", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sacred Lance", character: "Athena", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Mobius Strip", character: "Clarisse", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Brahma Gauntlet", character: "Ghandagoza", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Draco Claw", character: "Grea", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Arjunan Bow", character: "Ilsa (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sunflower Wand", character: "Io (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Feendrache Pennant", character: "Lancelot and Vane", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Illusion Scepter", character: "Magisa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Roseate Aetherial Bow", character: "Metera", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Antwerp", character: "Percival (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Two by Four", character: "Tsubasa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Thunder Dirk Jove", character: "Agielba", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Magma Gauntlet", character: "Aliza", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Benedia", character: "Rackam (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Blushing Blossom Pin", character: "Societte (Fire)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Starblaze Rings", character: "Zahlhamelina", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Brionac", character: "Zeta", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Forbidden Inferno", character: "Anthuria", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Snack Pole", character: "Danua (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Luin", character: "Heles", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Delta Apex", character: "Beatrix (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Nature's Mystery", character: "Dante (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Glass Bow", character: "Sutera (Fire)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Akhu", character: "Abby", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Kaister Knuckles", character: "Alec", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ember Blade", character: "Carren", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Dolphin", character: "Cucouroux", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Rope Knuckles", character: "Ghandagoza (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wandering Blade", character: "Lucius (Fire)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Time-Tested Iron", character: "Rosine (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Crimson Talons", character: "Sen", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Scarlet Oath", character: "Teena (Valentine)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Soulbound Dirk", character: "Teena", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tanzanite Sword Mikoh", character: "Therese", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Arson Link", character: "Blazing Teacher Elmott", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Deathly Arson", character: "Elmott (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Red-Hot Noodles", character: "Ippatsu (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Signal Flare", character: "Karva (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Fire Piece", character: "Mary (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Massive Axe", character: "Ryan (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Witch's Broom", character: "Anna (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Custom Arquebus", character: "Jessica (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Cup and Saucer", character: "Dorothy", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Arson", character: "Elmott", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Chain Knuckles", character: "Ezecrain", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Forest Hermit Staff", character: "Dante", rarity: "R")
Summon.create(summontype: "Character", weapon: "Derringer", character: "Barawa", rarity: "R")
Summon.create(summontype: "Character", weapon: "Cold Noodles", character: "Ippatsu (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Little Scarlet", character: "Drusilla", rarity: "R")
Summon.create(summontype: "Character", weapon: "Flame Bow", character: "Flesselles", rarity: "R")
Summon.create(summontype: "Character", weapon: "Chopsticks", character: "Ippatsu", rarity: "R")
Summon.create(summontype: "Character", weapon: "Flame Bolt", character: "Karva", rarity: "R")
Summon.create(summontype: "Character", weapon: "Vintage Flat Iron", character: "Rosine", rarity: "R")
Summon.create(summontype: "Character", weapon: "Feather Wand", character: "Anna", rarity: "R")
Summon.create(summontype: "Character", weapon: "Torch", character: "Camieux", rarity: "R")
Summon.create(summontype: "Character", weapon: "Firecracker", character: "Mary (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Soldier Axe", character: "Ryan", rarity: "R")
Summon.create(summontype: "Character", weapon: "Iron Pliers", character: "Viceroy", rarity: "R")
Summon.create(summontype: "Character", weapon: "Cursed Flame Candelabra", character: "Anna (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Ghillie Fork", character: "Elmelaura", rarity: "R")
Summon.create(summontype: "Character", weapon: "Broken Bottle", character: "Lamretta (R)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Petronel", character: "Mary", rarity: "R")

Summon.create(summontype: "Character", weapon: "Dainsleif", character: "Altair", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Blue Sphere", character: "Drang", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Galilei's Insight", character: "Europa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Draco Horn", character: "Grea (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Vlisragna", character: "Silva", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Canisius", character: "Vajra", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Izayoi", character: "Yuel (Water)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gottfried", character: "Aglovale", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Daemon's Spine", character: "Anne", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Stardust Holly Rod", character: "Arulumaya (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Claíomh Solais", character: "Charlotta", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tlepilli", character: "Diantha (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Frostbite", character: "Izmir (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Nagelring", character: "Izmir", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Murgleis", character: "Katalina (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Hoarfrost Blade Persius", character: "Lancelot", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ice Crystal Staff", character: "Lily", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Raikiri", character: "Narmaya (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Taisai Spirit Bow", character: "Pholia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Montague's Oath", character: "Romeo", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Blossom Axe", character: "Vane (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Meteora", character: "Yngwie", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Fudo-Kuniyuki", character: "Yodarha (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Phantom Thief Blade", character: "Chat Noir", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "White Hawk", character: "Cucouroux (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Metal Hand", character: "Lady Katapillar and Vira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Melodic Sphere", character: "Lilele", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Froststar Staff", character: "Macula Marius", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Scarlet Vane", character: "Societte", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sword of Sorcery", character: "Owen", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aquarium Harp", character: "Ejaeli", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ripple Rapier", character: "Katalina (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aquablade", character: "Mina", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Epoxy Boogie Plates", character: "Cailana (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Floaty Sword", character: "Charlotta (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Royal Rapier", character: "Ange", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Water Balloons", character: "Camieux (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ice Bough Staff", character: "Erin", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Macuahuitl", character: "Farrah (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Quarrel", character: "Sahli Lao", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Titanium Harpoon", character: "Sig", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sunshade Parasol", character: "Suframare (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Narval", character: "Ulamnuran", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Bottle o' Blossoms", character: "Lamretta (Water)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Summer Beach Sphere", character: "Lilele (WSummer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ice Bow", character: "Milleore", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Spritewood Staff", character: "Mishra", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Colorful Crackerjack", character: "Pengy", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Raging Halberd", character: "Vane", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Boogie Plates", character: "Cailana", rarity: "R")
Summon.create(summontype: "Character", weapon: "White Sword", character: "Bridgette", rarity: "R")
Summon.create(summontype: "Character", weapon: "Tattoo Fist", character: "Randall", rarity: "R")
Summon.create(summontype: "Character", weapon: "Silver Pole", character: "Joel", rarity: "R")
Summon.create(summontype: "Character", weapon: "Snowman Rod", character: "Suframare", rarity: "R")
Summon.create(summontype: "Character", weapon: "Student Notenbook", character: "Alistair", rarity: "R")
Summon.create(summontype: "Character", weapon: "Night Horn", character: "Deliford", rarity: "R")
Summon.create(summontype: "Character", weapon: "Shrimp Lure", character: "Yodarha", rarity: "R")
Summon.create(summontype: "Character", weapon: "Self Defender", character: "Richard", rarity: "R")

Summon.create(summontype: "Character", weapon: "Mirror-Blade Shard", character: "Alexiel", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ancient Bandages", character: "Ayer", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ichigo Hitofuri", character: "Cain (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Neko Punch Pro", character: "Dante and Freiheit", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ascalon", character: "Siegfried", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Greatsword Andalius", character: "Aletheia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gargantua", character: "Arulumaya", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ouroboros", character: "Cagliostro", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Thyrsus", character: "De La Fille (Earth)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Stratomizer", character: "Eustace", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Soul Eater", character: "Hallessena", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gallinarius", character: "Mahira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Medusiana Staff", character: "Medusa (Valentine)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Thorny Rose", character: "Rosetta (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sandcastle Song-Lume", character: "Sara", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Wurtzite Scythe", character: "Vaseraga (Earth)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Arsene", character: "Catherine", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Snow Mobius Strip", character: "Clarisse (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "AK-4A", character: "Eugen (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Nightmare Mobilizer", character: "Eustance (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gandiva", character: "Ilsa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Mettle", character: "Nemone", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gae Derg", character: "Razia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Wyrmtiger Claw", character: "Soriz (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Bella Aeterna", character: "Yggdrasil", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Euripedes", character: "Medusa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Vassago", character: "Melleau", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Deep Desire", character: "Vira (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tughril", character: "NezaHualpilli (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tropical Punch", character: "Ayer", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ram-Dao", character: "Gayne", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Shrike's Beak", character: "Jamil", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Flower Crown", character: "Jasmine (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Gold-Plated Fremel", character: "Almeida (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Prideful Sword", character: "Beatrix (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Great Hammer", character: "Galadar (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Grand Edge", character: "Herja (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Serpentine Longspear", character: "Leona", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Heavy-Duty Pumpkins", character: "Mimlemel and Pun-Kin (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Divine Spear", character: "Razia (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Giant Fork", character: "Redluck", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ripple Harp", character: "Sara (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Impact Knuckles", character: "Soriz", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Macho Hunter Weapon", character: "The Lowain Bros", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Fremel Hammer", character: "Almeida", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Demitasse", character: "Catherine (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Silver Rings", character: "J.J. (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Handy Arquebus", character: "Jessica", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tyrian Tiger Blade", character: "Jin (Themed)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Obsidian Bow", character: "Jin (Event)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Metal Glove", character: "Ladiva", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Zhonpeli", character: "Lamretta", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Mythril Tonfa", character: "Vanzza (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sudarshana", character: "Carmelina (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Golden Mop", character: "Claudia", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Desert Arms", character: "Egen (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Dreadflayer", character: "Laguna", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Flare Glaive", character: "Mariah", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Holy Harp", character: "Rackam (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sword of Lisblanc", character: "Farrah (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sandcastle Spear", character: "Sara (Event)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Iron Guard", character: "Balurga", rarity: "R")
Summon.create(summontype: "Character", weapon: "Heavy Metal Comb", character: "La Coiffe", rarity: "R")
Summon.create(summontype: "Character", weapon: "Rubia Rod", character: "Camieux (Earth)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Draph Hammer", character: "Galadar", rarity: "R")
Summon.create(summontype: "Character", weapon: "Xiphos", character: "Volenna", rarity: "R")
Summon.create(summontype: "Character", weapon: "Sawed-Off Shotgun", character: "Garma", rarity: "R")
Summon.create(summontype: "Character", weapon: "Two-Handed Sword", character: "Herja", rarity: "R")
Summon.create(summontype: "Character", weapon: "Oven Mitts", character: "Nene", rarity: "R")
Summon.create(summontype: "Character", weapon: "Stone Pole", character: "Norcel", rarity: "R")
Summon.create(summontype: "Character", weapon: "Tonfa", character: "Vanzza", rarity: "R")
Summon.create(summontype: "Character", weapon: "Fire Sword", character: "Farrah", rarity: "R")
Summon.create(summontype: "Character", weapon: "Taiaha", character: "Jasmine", rarity: "R")
Summon.create(summontype: "Character", weapon: "Wooden Dagger", character: "Walder (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Tree Wand", character: "Walder (Holiday)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Main Gauche", character: "Walder", rarity: "R")

Summon.create(summontype: "Character", weapon: "Dormius", character: "Andira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Vortex of the Void", character: "Grimnir", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Deirdre's Symbol", character: "Heles (Wind)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Orleans Standard", character: "Jeanne d'Arc (Themed)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Reunion", character: "Lecia (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Returner Staff", character: "Yurius", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Windflash", character: "Gawain", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Wing of the Pure", character: "Korwa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Heiliges Schwert", character: "Lancelot (Wind)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Far Away", character: "Lennah", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Split End", character: "Melissabelle", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Aetherial Bow", character: "Metera", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Pilum", character: "Nezahualpilli", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Love Eternal", character: "Rosetta (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Deirdre's Claws", character: "Scathacha", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Cythara Anglica", character: "Selfira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Galactic Impact", character: "Sen (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sinensis", character: "Siegfried (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Another Sky", character: "Vira (Wind)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Crimson Sapphire", character: "Yuel (Themed)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Yyrkoon", character: "Yuisis", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Cords of Heaven Lillah", character: "Arriet", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Heroic Bow", character: "Feena", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Bell of Happy Endings", character: "Korwa (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Heaven's Cloud", character: "Petra (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tiamat Bolt Prime", character: "Tiamat", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Turpin Spear", character: "Carmelina", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Kilij", character: "Juri", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Unsigned Blade", character: "Mirin", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Zanbatto", character: "Sevilbarra", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Festive Frying Pan", character: "Yaia (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tilvung", character: "Helnar", rarity: "SR")
Summon.create(summontype: "Character", weapon: "White Flag", character: "Mimlemel and Stumpeye", rarity: "SR")
Summon.create(summontype: "Character", weapon: "White Talons", character: "Sen (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Holy Axe", character: "Sevastien", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sutera's Bow", character: "Sutera", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Summer Souteyrand", character: "Yuisis (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Balisarde", character: "Arthur and Mordred", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Seaside Memory", character: "Chloe (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sahdow Scepter", character: "Goblin Mage", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Merciless Chastening", character: "Hazen (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Silver Fan", character: "Karteira (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Stravaria", character: "Keehar", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tiger Fang", character: "Mimlemel", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Standard Albion Bolt", character: "Tyre", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Cloud Tomahawk", character: "Eso (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Skirt Chaser", character: "Helnar (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Priate Sword", character: "Lecia (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Songsmith's Harp", character: "Elta", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Jeunesse", character: "Korwa(SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Enchanted Nail", character: "Chloe", rarity: "R")
Summon.create(summontype: "Character", weapon: "Practice Sword", character: "Thelonim", rarity: "R")
Summon.create(summontype: "Character", weapon: "Paper Fan", character: "Karteira", rarity: "R")
Summon.create(summontype: "Character", weapon: "Moss Tree Staff", character: "Petra", rarity: "R")
Summon.create(summontype: "Character", weapon: "Lightbringer", character: "Stan", rarity: "R")
Summon.create(summontype: "Character", weapon: "Sky Tomahawk", character: "Eso", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mythril Knuckles", character: "Hazen", rarity: "R")
Summon.create(summontype: "Character", weapon: "Dark Sword", character: "Leonora", rarity: "R")
Summon.create(summontype: "Character", weapon: "Light Buckler", character: "Pavidus", rarity: "R")
Summon.create(summontype: "Character", weapon: "Old Sword", character: "Krugne", rarity: "R")

Summon.create(summontype: "Character", weapon: "Hauteclaire", character: "Albert", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Claidheamh Soluis", character: "Charlotta (Light)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Fusion Mobius", character: "Clarisse (Light)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Eden", character: "Lucio", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Pinkie Needle", character: "Metera (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Conifer", character: "Naoise (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Railgun", character: "Robomi", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Hrotti", character: "Sereul", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Certificus", character: "Vira (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Dragon Slayer", character: "Amira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gothic Cutlery", character: "Dorothy and Claudia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ethereal Lasher", character: "Ferry (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Crystal Luin", character: "Heles (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gambanteinn", character: "Io (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Caladbolg", character: "Jeanne d'Arc", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Capulet's Oath", character: "Juliet", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Porculius", character: "Kumbhira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Levin Shooter", character: "Levin Sisters", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Jolly Starcracker", character: "Mary (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Twin Helix", character: "Rosamia (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sealed Claustrum", character: "Sarunan", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Full Metal Recoil", character: "Silva (Light)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Cletine", character: "Zeta (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ruler of Fate", character: "Zooey", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Symbol of Justice", character: "Baotorda (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Kerykeion", character: "De La Fille", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Diamond Edge", character: "De La Fille (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sword on the Cob", character: "Melissabelle (Valentine)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ocean Harp", character: "Sophia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Jack-O'-Brand", character: "Charlotta (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Heavy Blast Knuckles", character: "Feather (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Lance d'Espoir", character: "Jeanne d'Arc (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Samurai Sword", character: "Mirin (Light)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "True Teardrop", character: "Vermeil (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aerial Cane", character: "Arusha", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Winter Wonderbow", character: "Feena (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wind-Rhyme Staff", character: "Noa", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Soothing Torch", character: "Rosamia (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Staff of the Star Seeker", character: "Sophia (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Arondight", character: "Baotorda", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Crocskin Glove", character: "Barawa (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Golden Woofer", character: "Daetta (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sacred Codex", character: "Johann", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Holy Glove", character: "Ladiva (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Humming Bard", character: "Elta (Light)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aura Whip", character: "Ferry (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Soul Edge", character: "Ferry", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Misanga Bracelet", character: "J.J.", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Slingshot", character: "Sarya", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Blue Crest", character: "Cordelia", rarity: "R")
Summon.create(summontype: "Character", weapon: "Prism Tear", character: "Vermeil", rarity: "R")
Summon.create(summontype: "Character", weapon: "Morning Star", character: "Daetta", rarity: "R")
Summon.create(summontype: "Character", weapon: "Light Staff", character: "Philosophia", rarity: "R")
Summon.create(summontype: "Character", weapon: "Blast Knuckles", character: "Feather", rarity: "R")
Summon.create(summontype: "Character", weapon: "Thunder Rapier", character: "Rosamia", rarity: "R")

Summon.create(summontype: "Character", weapon: "Cute Ribbon", character: "Zooey (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Shadow Viperlance", character: "Azazel", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Unheil", character: "Ferry (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Disparia", character: "Jeanne d'Arc (Dark)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Distant Requiem", character: "Lady Grey (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Venustas", character: "Narmaya", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Fallen Sword", character: "Olivia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Parazonium", character: "Orchid", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Master Key", character: "Wulf and Renie", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gram", character: "Beatrix", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Blutgang", character: "Black Knight", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Silphium", character: "Clarisse (Valentine)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ishtar", character: "Eustace (Dark)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ukonvasara", character: "Lady Grey", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gigante Slicer", character: "Nicholas", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gandring", character: "Tanya (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Azoth", character: "Vania", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Mistilteinn", character: "Vaseraga", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Bloody Scar", character: "Veight", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Lyst Sin", character: "Vira (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sunspot Spear", character: "Zeta (Dark)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Black Ouroboros", character: "Cagliostro (Dark)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Coco & Mimi", character: "Cerberus", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Mikazuki", character: "Danua (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Skyrend Spear", character: "Forte", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ruling Pen", character: "Lunalu (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gridarvor", character: "Marquiares", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Rosen Maiden", character: "Rosetta (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ouroboros Treat", character: "Cagliostro (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Arachne", character: "Freezie", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Summer Night Peak", character: "Arulumaya (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Phantom Gauntlet", character: "Feather (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Cruel Claw", character: "Predator", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Genius Squared", character: "Skull", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Vampire's Nail", character: "Vania (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Cursed Cane", character: "Will (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Puppet Knife", character: "Danua", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Brocken Lance", character: "Deliford (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Katzbalger", character: "Jamil (Dark)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Voulge", character: "Zaja", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Purity Blade", character: "Lucius", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Silver Shotel", character: "Randall (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Shade Knife", character: "Tanya (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wyrm Claw", character: "Tanya (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Dracula Harp", character: "Ange (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Confection Cutter", character: "Narmaya (Valentine)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Scalpel", character: "Shao", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Hunter's Rifle", character: "Ludmila", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Goldie", character: "Richard (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Night Bell", character: "Lunalu", rarity: "R")
Summon.create(summontype: "Character", weapon: "Night Air Bell", character: "Lunalu (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Switchblade", character: "Lowain", rarity: "R")
Summon.create(summontype: "Character", weapon: "Cleaver", character: "Lowain (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Bronze Bell", character: "Bakura", rarity: "R")
Summon.create(summontype: "Character", weapon: "Bloody Piercer", character: "Tanya", rarity: "R")
Summon.create(summontype: "Character", weapon: "Zehek", character: "Mandau", rarity: "R")
Summon.create(summontype: "Character", weapon: "The Cross", character: "Will", rarity: "R")
