# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Summon.create(summontype: "Character", weapon: "Ramulus", event: "Grand", character: "Anila", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Purifying Thunderbolt", event: "Flash", character: "Shiva", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Delta Quartz", event: "Summer", character: "Beatrix (Themed)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Lohengrin", event: "None", character: "Percival", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ixaba", event: "Flash", character: "Sturm", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tanzanite Blade", event: "None", character: "Therese (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Scarlet Crest Axe", event: "None", character: "Yuel", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sacred Lance", event: "None", character: "Athena", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Mobius Strip", event: "None", character: "Clarisse", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Brahma Gauntlet", event: "None", character: "Ghandagoza", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Draco Claw", event: "None", character: "Grea", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Arjunan Bow", event: "Summer", character: "Ilsa (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sunflower Wand", event: "Summer", character: "Io (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Feendrache Pennant", event: "None", character: "Lancelot and Vane", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Illusion Scepter", event: "None", character: "Magisa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Roseate Aetherial Bow", event: "None", character: "Metera", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Antwerp", event: "Summer", character: "Percival (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Two-by-Four", event: "None", character: "Tsubasa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Thunder Dirk Jove", event: "None", character: "Agielba", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Magma Gauntlet", event: "None", character: "Aliza", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Benedia", event: "Grand", character: "Rackam (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Blushing Blossom Pin", event: "None", character: "Societte (Fire)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Starblaze Rings", event: "None", character: "Zahlhamelina", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Brionac", event: "None", character: "Zeta", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Forbidden Inferno", event: "None", character: "Anthuria", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Snack Pole", event: "Halloween", character: "Danua (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Luin", event: "None", character: "Heles", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Delta Apex", event: "Halloween", character: "Beatrix (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Nature's Mystery", event: "None", character: "Dante (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Glass Bow", event: "None", character: "Sutera (Fire)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Akhu", event: "None", character: "Abby", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Kaiser Knuckles", event: "None", character: "Alec", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ember Blade", event: "None", character: "Carren", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Dolphin", event: "None", character: "Cucouroux", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Rope Knuckles", event: "Summer", character: "Ghandagoza (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wandering Blade", event: "None", character: "Lucius (Fire)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Time-Tested Iron", event: "None", character: "Rosine (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Crimson Talons", event: "None", character: "Sen", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Scarlet Oath", event: "Valentine", character: "Teena (Valentine)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Soulbound Dirk", event: "None", character: "Teena", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tanzanite Sword Mikoh", event: "None", character: "Therese", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Arson Link", event: "None", character: "Blazing Teacher Elmott", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Deathly Arson", event: "Summer", character: "Elmott (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Red-Hot Noodles", event: "None", character: "Ippatsu (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Signal Flare", event: "None", character: "Karva (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Fire Piece", event: "None", character: "Mary (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Massive Axe", event: "None", character: "Ryan (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Witch's Broom", event: "None", character: "Anna (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Custom Arquebus", event: "Summer", character: "Jessica (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Cup and Saucer", event: "None", character: "Dorothy", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Arson", event: "None", character: "Elmott", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Chain Knuckles", event: "None", character: "Ezecrain", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Mythril Bolt", event: "None", character: "Aster", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Forest Hermit Staff", event: "None", character: "Dante", rarity: "R")
Summon.create(summontype: "Character", weapon: "Derringer", event: "None", character: "Barawa", rarity: "R")
Summon.create(summontype: "Character", weapon: "Cold Noodles", event: "Summer", character: "Ippatsu (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Little Scarlet", event: "None", character: "Drusilla", rarity: "R")
Summon.create(summontype: "Character", weapon: "Flame Bow", event: "None", character: "Flesselles", rarity: "R")
Summon.create(summontype: "Character", weapon: "Chopsticks", event: "None", character: "Ippatsu", rarity: "R")
Summon.create(summontype: "Character", weapon: "Flame Bolt", event: "None", character: "Karva", rarity: "R")
Summon.create(summontype: "Character", weapon: "Vintage Flat Iron", event: "None", character: "Rosine", rarity: "R")
Summon.create(summontype: "Character", weapon: "Feather Wand", event: "None", character: "Anna", rarity: "R")
Summon.create(summontype: "Character", weapon: "Torch", event: "None", character: "Camieux", rarity: "R")
Summon.create(summontype: "Character", weapon: "Firecracker", event: "Summer", character: "Mary (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Soldier Axe", event: "None", character: "Ryan", rarity: "R")
Summon.create(summontype: "Character", weapon: "Iron Pliers", event: "None", character: "Viceroy", rarity: "R")
Summon.create(summontype: "Character", weapon: "Cursed Flame Candelabra", event: "Summer", character: "Anna (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Ghillie Fork", event: "None", character: "Elmelaura", rarity: "R")
Summon.create(summontype: "Character", weapon: "Broken Bottle", event: "None", character: "Lamretta (R)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Petronel", event: "None", character: "Mary", rarity: "R")

Summon.create(summontype: "Character", weapon: "Dainsleif", event: "None", character: "Altair", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Blue Sphere", event: "Flash", character: "Drang", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Galilei's Insight", event: "Flash", character: "Europa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Draco Horn", event: "Summer", character: "Grea (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Vlisragna", event: "None", character: "Silva", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Canisius", event: "Grand", character: "Vajra", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Izayoi", event: "None", character: "Yuel (Water)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gottfried", event: "None", character: "Aglovale", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Daemon's Spine", event: "None", character: "Anne", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Stardust Holly Rod", event: "Holiday", character: "Arulumaya (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Claíomh Solais", event: "None", character: "Charlotta", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tlepilli", event: "Summer", character: "Diantha (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Frostbite", event: "Summer", character: "Izmir (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Nagelring", event: "None", character: "Izmir", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Murgleis", event: "Grand", character: "Katalina (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Hoarfrost Blade Persius", event: "None", character: "Lancelot", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ice Crystal Staff", event: "None", character: "Lily", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Raikiri", event: "Summer", character: "Narmaya (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Taisai Spirit Bow", event: "Grand", character: "Pholia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Montague's Oath", event: "None", character: "Romeo", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Blossom Axe", event: "None", character: "Vane (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Meteora", event: "None", character: "Yngwie", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Fudo-Kuniyuki", event: "None", character: "Yodarha (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Phantom Thief Blade", event: "None", character: "Chat Noir", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "White Hawk", event: "None", character: "Cucouroux (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Metal Hand", event: "None", character: "Lady Katapillar and Vira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Melodic Sphere", event: "None", character: "Lilele", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Froststar Staff", event: "None", character: "Macula Marius", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Scarlet Vane", event: "None", character: "Societte", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ain Soph", event: "Summer", character: "Sandalphon (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sword of Sorcery", event: "None", character: "Owen", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aquarium Harp", event: "None", character: "Ejaeli", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ripple Rapier", event: "Summer", character: "Katalina (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aquablade", event: "None", character: "Mina", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Epoxy Boogie Plates", event: "None", character: "Cailana (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Floaty Sword", event: "Summer", character: "Charlotta (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Royal Rapier", event: "None", character: "Ange", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Water Balloons", event: "Summer", character: "Camieux (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ice Bough Staff", event: "None", character: "Erin", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Macuahuitl", event: "Summer", character: "Farrah (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Quarrel", event: "None", character: "Sahli Lao", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Titanium Harpoon", event: "None", character: "Sig", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sunshade Parasol", event: "Summer", character: "Suframare (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Narval", event: "None", character: "Ulamnuran", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Bottle o' Blossoms", event: "None", character: "Lamretta (Water)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Summer Beach Sphere", event: "Summer", character: "Lilele (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ice Bow", event: "None", character: "Milleore", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Spritewood Staff", event: "None", character: "Mishra", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Colorful Crackerjack", event: "None", character: "Pengy", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Raging Halberd", event: "None", character: "Vane", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Boogie Plates", event: "None", character: "Cailana", rarity: "R")
Summon.create(summontype: "Character", weapon: "White Sword", event: "None", character: "Bridgette", rarity: "R")
Summon.create(summontype: "Character", weapon: "Tattoo Fist", event: "None", character: "Randall", rarity: "R")
Summon.create(summontype: "Character", weapon: "Silver Pole", event: "None", character: "Joel", rarity: "R")
Summon.create(summontype: "Character", weapon: "Snowman Rod", event: "None", character: "Suframare", rarity: "R")
Summon.create(summontype: "Character", weapon: "Student Notebook", event: "None", character: "Alistair", rarity: "R")
Summon.create(summontype: "Character", weapon: "Night Horn", event: "None", character: "Deliford", rarity: "R")
Summon.create(summontype: "Character", weapon: "Shrimp Lure", event: "None", character: "Yodarha", rarity: "R")
Summon.create(summontype: "Character", weapon: "Self Defender", event: "None", character: "Richard", rarity: "R")

Summon.create(summontype: "Character", weapon: "Mirror-Blade Shard", event: "Flash", character: "Alexiel", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ancient Bandages", event: "None", character: "Ayer", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ichigo Hitofuri", event: "Grand", character: "Cain (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Neko Punch Pro", event: "None", character: "Dante and Freiheit", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ascalon", event: "None", character: "Siegfried", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Greatsword Andalius", event: "None", character: "Aletheia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gargantua", event: "None", character: "Arulumaya", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ouroboros", event: "None", character: "Cagliostro", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Thyrsus", event: "None", character: "De La Fille (Earth)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Stratomizer", event: "None", character: "Eustace", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Soul Eater", event: "None", character: "Hallessena", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gallinarius", event: "Grand", character: "Mahira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Medusiana Staff", event: "Valentine", character: "Medusa (Valentine)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Thorny Rose", event: "Summer", character: "Rosetta (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sandcastle Song-Lume", event: "None", character: "Sara", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Wurtzite Scythe", event: "None", character: "Vaseraga (Earth)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Arsene", event: "None", character: "Catherine", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Snow Mobius Strip", event: "Holiday", character: "Clarisse (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "AK-4A", event: "Grand", character: "Eugen (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Nightmare Mobilizer", event: "Halloween", character: "Eustance (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gandiva", event: "None", character: "Ilsa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Mettle", event: "None", character: "Nemone", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gae Derg", event: "None", character: "Razia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Wyrmtiger Claw", event: "None", character: "Soriz (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Bella Aeterna", event: "None", character: "Yggdrasil", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Euripedes", event: "None", character: "Medusa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Vassago", event: "None", character: "Melleau", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Deep Desire", event: "Summer", character: "Vira (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Spymur's Clause", event: "None", character: "Baal", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Rainbow Hand", event: "None", character: "Ladiva (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tughril", event: "None", character: "NezaHualpilli (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tropical Punch", event: "Summer", character: "Ayer", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ram-Dao", event: "None", character: "Gayne", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Shrike's Beak", event: "None", character: "Jamil", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Flower Crown", event: "None", character: "Jasmine (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Gold-Plated Fremel", event: "Summer", character: "Almeida (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Prideful Sword", event: "None", character: "Beatrix (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Great Hammer", event: "None", character: "Galadar (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Grand Edge", event: "None", character: "Herja (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Serpentine Longspear", event: "None", character: "Leona", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Heavy-Duty Pumpkins", event: "Halloween", character: "Mimlemel and Pun-Kin (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Divine Spear", event: "None", character: "Razia (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Giant Fork", event: "None", character: "Redluck", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ripple Harp", event: "Summer", character: "Sara (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Impact Knuckles", event: "None", character: "Soriz", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Macho Hunter Weapon", event: "None", character: "The Lowain Bros", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Fremel Hammer", event: "None", character: "Almeida", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Demitasse", event: "None", character: "Catherine (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Silver Rings", event: "Summer", character: "J.J. (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Handy Arquebus", event: "None", character: "Jessica", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tyrian Tiger Blade", event: "Summer", character: "Jin (Themed)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Metal Glove", event: "None", character: "Ladiva", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Zhonpeli", event: "None", character: "Lamretta", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Mythril Tonfa", event: "None", character: "Vanzza (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sudarshana", event: "None", character: "Carmelina (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Golden Mop", event: "None", character: "Claudia", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Desert Arms", event: "Summer", character: "Egen (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Dreadflayer", event: "None", character: "Laguna", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Flare Glaive", event: "None", character: "Mariah", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Holy Harp", event: "Holiday", character: "Rackam (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sword of Lisblanc", event: "None", character: "Farrah (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Iron Guard", event: "None", character: "Balurga", rarity: "R")
Summon.create(summontype: "Character", weapon: "Heavy Metal Comb", event: "None", character: "La Coiffe", rarity: "R")
Summon.create(summontype: "Character", weapon: "Rubia Rod", event: "None", character: "Camieux (Earth)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Draph Hammer", event: "None", character: "Galadar", rarity: "R")
Summon.create(summontype: "Character", weapon: "Xiphos", event: "None", character: "Volenna", rarity: "R")
Summon.create(summontype: "Character", weapon: "Sawed-Off Shotgun", event: "None", character: "Garma", rarity: "R")
Summon.create(summontype: "Character", weapon: "Two-Handed Sword", event: "None", character: "Herja", rarity: "R")
Summon.create(summontype: "Character", weapon: "Oven Mitts", event: "None", character: "Nene", rarity: "R")
Summon.create(summontype: "Character", weapon: "Stone Pole", event: "None", character: "Norcel", rarity: "R")
Summon.create(summontype: "Character", weapon: "Tonfa", event: "None", character: "Vanzza", rarity: "R")
Summon.create(summontype: "Character", weapon: "Fire Sword", event: "None", character: "Farrah", rarity: "R")
Summon.create(summontype: "Character", weapon: "Taiaha", event: "None", character: "Jasmine", rarity: "R")
Summon.create(summontype: "Character", weapon: "Wooden Dagger", event: "Summer", character: "Walder (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Tree Wand", event: "Holiday", character: "Walder (Holiday)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Main Gauche", event: "None", character: "Walder", rarity: "R")

Summon.create(summontype: "Character", weapon: "Dormius", event: "Grand", character: "Andira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Vortex of the Void", event: "Flash", character: "Grimnir", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Deirdre's Symbol", event: "None", character: "Heles (Wind)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Orleans Standard", event: "Summer", character: "Jeanne d'Arc (Themed)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Reunion", event: "Grand", character: "Lecia (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Returner Staff", event: "None", character: "Yurius", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Windflash", event: "None", character: "Gawain", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Wing of the Pure", event: "None", character: "Korwa", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Heiliges Schwert", event: "None", character: "Lancelot (Wind)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Far Away", event: "None", character: "Lennah", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Split End", event: "None", character: "Melissabelle", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Aetherial Bow", event: "None", character: "Metera", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Pilum", event: "None", character: "Nezahualpilli", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Love Eternal", event: "Grand", character: "Rosetta (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Deirdre's Claws", event: "None", character: "Scathacha", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Cythara Anglica", event: "None", character: "Selfira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Galactic Impact", event: "None", character: "Sen (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sinensis", event: "Summer", character: "Siegfried (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Another Sky", event: "None", character: "Vira (Wind)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Crimson Sapphire", event: "Summer", character: "Yuel (Themed)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Yyrkoon", event: "None", character: "Yuisis", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Cords of Heaven Lillah", event: "None", character: "Arriet", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Heroic Bow", event: "None", character: "Feena", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Bell of Happy Endings", event: "Summer", character: "Korwa (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Heaven's Cloud", event: "None", character: "Petra (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tiamat Bolt Prime", event: "None", character: "Tiamat", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Turpin Spear", event: "None", character: "Carmelina", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Turpin Spear", event: "None", character: "Morrigna", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Kilij", event: "None", character: "Juri", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Unsigned Blade", event: "None", character: "Mirin", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Zanbato", event: "None", character: "Sevilbarra", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Festive Frying Pan", event: "Holiday", character: "Yaia (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tilvung", event: "None", character: "Helnar", rarity: "SR")
Summon.create(summontype: "Character", weapon: "White Flag", event: "None", character: "Mimlemel and Stumpeye", rarity: "SR")
Summon.create(summontype: "Character", weapon: "White Talons", event: "Holiday", character: "Sen (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Holy Axe", event: "None", character: "Sevastien", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sutera's Bow", event: "None", character: "Sutera", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Summer Souteyrand", event: "Summer", character: "Yuisis (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Balisarde", event: "None", character: "Arthur and Mordred", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Seaside Memory", event: "Summer", character: "Chloe (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Shadow Scepter", event: "None", character: "Goblin Mage", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Merciless Chastening", event: "None", character: "Hazen (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Silver Fan", event: "None", character: "Karteira (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Stravaria", event: "None", character: "Keehar", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Tiger Fang", event: "None", character: "Mimlemel", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Standard Albion Bolt", event: "None", character: "Tyre", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Cloud Tomahawk", event: "None", character: "Eso (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Skirt Chaser", event: "Summer", character: "Helnar (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Priate Sword", event: "Summer", character: "Lecia (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Songsmith's Harp", event: "None", character: "Elta", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Jeunesse", event: "None", character: "Korwa (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Enchanted Nail", event: "None", character: "Chloe", rarity: "R")
Summon.create(summontype: "Character", weapon: "Practice Sword", event: "None", character: "Thelonim", rarity: "R")
Summon.create(summontype: "Character", weapon: "Paper Fan", event: "None", character: "Karteira", rarity: "R")
Summon.create(summontype: "Character", weapon: "Moss Tree Staff", event: "None", character: "Petra", rarity: "R")
Summon.create(summontype: "Character", weapon: "Lightbringer", event: "None", character: "Stan", rarity: "R")
Summon.create(summontype: "Character", weapon: "Sky Tomahawk", event: "None", character: "Eso", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mythril Knuckles", event: "None", character: "Hazen", rarity: "R")
Summon.create(summontype: "Character", weapon: "Dark Sword", event: "None", character: "Leonora", rarity: "R")
Summon.create(summontype: "Character", weapon: "Light Buckler", event: "None", character: "Pavidus", rarity: "R")
Summon.create(summontype: "Character", weapon: "Old Sword", event: "None", character: "Krugne", rarity: "R")

Summon.create(summontype: "Character", weapon: "Hauteclaire", event: "None", character: "Albert", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Claidheamh Soluis", event: "None", character: "Charlotta (Light)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Fusion Mobius", event: "None", character: "Clarisse (Light)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Eden", event: "Flash", character: "Lucio", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Pinkie Needle", event: "Holiday", character: "Metera (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Conifer", event: "Summer", character: "Naoise (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Railgun", event: "None", character: "Robomi", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Hrotti", event: "None", character: "Sereul", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Certificus", event: "Grand", character: "Vira (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Dragon Slayer", event: "None", character: "Amira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gothic Cutlery", event: "None", character: "Dorothy and Claudia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ethereal Lasher", event: "None", character: "Ferry (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Crystal Luin", event: "Summer", character: "Heles (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gambanteinn", event: "Grand", character: "Io (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Caladbolg", event: "None", character: "Jeanne d'Arc", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Capulet's Oath", event: "None", character: "Juliet", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Porculius", event: "Grand", character: "Kumbhira", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Levin Shooter", event: "None", character: "Levin Sisters", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Jolly Starcracker", event: "Holiday", character: "Mary (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Twin Helix", event: "None", character: "Rosamia (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sealed Claustrum", event: "None", character: "Sarunan", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Full Metal Recoil", event: "None", character: "Silva (Light)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Cletine", event: "Summer", character: "Zeta (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ruler of Fate", event: "None", character: "Zooey", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Symbol of Justice", event: "None", character: "Baotorda (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Kerykeion", event: "None", character: "De La Fille", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Diamond Edge", event: "Summer", character: "De La Fille (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sword on the Cob", event: "Valentine", character: "Melissabelle (Valentine)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ocean Harp", event: "None", character: "Sophia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sharp Letter", event: "Summer", character: "Halluel and Malluel (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Jack-O'-Brand", event: "Halloween", character: "Charlotta (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Heavy Blast Knuckles", event: "None", character: "Feather (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Lance d'Espoir", event: "None", character: "Jeanne d'Arc (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Samurai Sword", event: "None", character: "Mirin (Light)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "True Teardrop", event: "None", character: "Vermeil (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aerial Cane", event: "None", character: "Arusha", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Winter Wonderbow", event: "Holiday", character: "Feena (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wind-Rhyme Staff", event: "None", character: "Noa", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Soothing Torch", event: "None", character: "Rosamia (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Staff of the Star Seeker", event: "None", character: "Sophia (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Arondight", event: "None", character: "Baotorda", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Crocskin Glove", event: "None", character: "Barawa (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Golden Woofer", event: "None", character: "Daetta (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sacred Codex", event: "None", character: "Johann", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Holy Glove", event: "Holiday", character: "Ladiva (Holiday)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Humming Bard", event: "None", character: "Elta (Light)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aura Whip", event: "Halloween", character: "Ferry (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Soul Edge", event: "None", character: "Ferry", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Misanga Bracelet", event: "None", character: "J.J.", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Slingshot", event: "None", character: "Sarya", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Staff of Refusal", event: "None", character: "Philosophia (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Lumiel Banner", event: "None", character: "Bridgette and Cordelia", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Blue Crest", event: "None", character: "Cordelia", rarity: "R")
Summon.create(summontype: "Character", weapon: "Prism Tear", event: "None", character: "Vermeil", rarity: "R")
Summon.create(summontype: "Character", weapon: "Morning Star", event: "None", character: "Daetta", rarity: "R")
Summon.create(summontype: "Character", weapon: "Light Staff", event: "None", character: "Philosophia", rarity: "R")
Summon.create(summontype: "Character", weapon: "Blast Knuckles", event: "None", character: "Feather", rarity: "R")
Summon.create(summontype: "Character", weapon: "Thunder Rapier", event: "None", character: "Rosamia", rarity: "R")

Summon.create(summontype: "Character", weapon: "Cute Ribbon", event: "Flash", character: "Zooey (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Shadow Viperlance", event: "None", character: "Azazel", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Unheil", event: "Grand", character: "Ferry (Grand)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Disparia", event: "None", character: "Jeanne d'Arc (Dark)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Distant Requiem", event: "Halloween", character: "Lady Grey (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Venustas", event: "None", character: "Narmaya", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Fallen Sword", event: "Flash", character: "Olivia", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Parazonium", event: "Flash", character: "Orchid", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Master Key", event: "None", character: "Wulf and Renie", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gram", event: "None", character: "Beatrix", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Blutgang", event: "Flash", character: "Black Knight", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Silphium", event: "Valentine", character: "Clarisse (Valentine)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ishtar", event: "None", character: "Eustace (Dark)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ukonvasara", event: "None", character: "Lady Grey", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gigante Slicer", event: "None", character: "Nicholas", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gandring", event: "None", character: "Tanya (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Azoth", event: "None", character: "Vania", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Mistilteinn", event: "None", character: "Vaseraga", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Bloody Scar", event: "None", character: "Veight", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Lyst Sin", event: "None", character: "Vira (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sunspot Spear", event: "None", character: "Zeta (Dark)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Black Ouroboros", event: "None", character: "Cagliostro (Dark)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Coco & Mimi", event: "None", character: "Cerberus", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Mikazuki", event: "Summer", character: "Danua (Summer)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Skyrend Spear", event: "None", character: "Forte", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ruling Pen", event: "None", character: "Lunalu (SSR)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gridarvor", event: "None", character: "Marquiares", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Rosen Maiden", event: "Holiday", character: "Rosetta (Holiday)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ouroboros Treat", event: "Halloween", character: "Cagliostro (Halloween)", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Arachne", event: "None", character: "Freezie", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Vagabond", event: "None", character: "Kolulu", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Summer Night Peak", event: "Summer", character: "Arulumaya (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Phantom Gauntlet", event: "Halloween", character: "Feather (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Cruel Claw", event: "None", character: "Predator", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Genius Squared", event: "None", character: "Skull", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Vampire's Nail", event: "None", character: "Vania (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Cursed Cane", event: "None", character: "Will (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Puppet Knife", event: "None", character: "Danua", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Brocken Lance", event: "None", character: "Deliford (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Katzbalger", event: "None", character: "Jamil (Dark)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Voulge", event: "None", character: "Zaja", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Purity Blade", event: "None", character: "Lucius", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Silver Shotel", event: "None", character: "Randall (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Shade Knife", event: "Summer", character: "Tanya (Summer)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wyrm Claw", event: "None", character: "Tanya (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Dracula Harp", event: "Halloween", character: "Ange (Halloween)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Confection Cutter", event: "Valentine", character: "Narmaya (Valentine)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Scalpel", event: "None", character: "Shao", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Hunter's Rifle", event: "None", character: "Ludmila", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Goldie", event: "None", character: "Richard (SR)", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Night Bell", event: "None", character: "Lunalu", rarity: "R")
Summon.create(summontype: "Character", weapon: "Night Air Bell", event: "Summer", character: "Lunalu (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Switchblade", event: "None", character: "Lowain", rarity: "R")
Summon.create(summontype: "Character", weapon: "Cleaver", event: "Summer", character: "Lowain (Summer)", rarity: "R")
Summon.create(summontype: "Character", weapon: "Bronze Bell", event: "None", character: "Bakura", rarity: "R")
Summon.create(summontype: "Character", weapon: "Bloody Piercer", event: "None", character: "Tanya", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mandau", event: "None", character: "Zehek", rarity: "R")
Summon.create(summontype: "Character", weapon: "The Cross", event: "None", character: "Will", rarity: "R")


Summon.create(summontype: "Character", weapon: "Fragarach", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Almace", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ilhoon", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Twisted Dagger", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Mirage Knife", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Stiletto", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Fusetto", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sword Breaker", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Trident", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Partisan", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Dragonfliar Cutter", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Shura Vhara", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Vajranda", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Bullova", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Shoka", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Horseman's Hammer", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Yagrush", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Pastoral Staff", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Holy Cane", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Dragon Tail", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wheellock Axe", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Crosswind", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Snaphance", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Swallowtail", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Mauler", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Neko Punch", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Jamadhar", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Imperial Bow", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sarnga", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aves", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Elfin Bow", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Shadow Bow", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Athanasius", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Iron Tiger", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Fluorithium Blade", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Sauria", event: "None", character: "None", rarity: "SR")

Summon.create(summontype: "Character", weapon: "Garnet Carbuncle", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Hellhound", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Hydra", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Vrazarek Firewyrm", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Angelie Cascade", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Aquamarine Carbuncle", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wilinus Icewyrm", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Clay Golem", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Doomworm", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Golem", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Myconid", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Ruination Gargoyle", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Stone Golem", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Zircon Carbuncle", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Elmenhilde Windsprite", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Elusious Windwyrm", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Griffin", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Wyvern", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Opal Carbuncle", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Pixie", event: "None", character: "None", rarity: "SR")
Summon.create(summontype: "Character", weapon: "Onyx Carbuncle", event: "None", character: "None", rarity: "SR")

Summon.create(summontype: "Character", weapon: "Anelace", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Claymore", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Falchion", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Flame Rapier", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Ice Sword", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Icey Nail", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Earth Cutlass", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Fire Baselard", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Kila", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mailbreaker", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Water Kukri", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Kris", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Emerald Dagger", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Leaf Dagger", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Holy Kris", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Assassin's Dagger", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Dark Knife", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Couse", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Fire Glaive", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Flame Halberd", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Langdebeve", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Aquan Killer", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Earth Halberd", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Halberd", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Harvester", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Battle Axe", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Earth Zaghnal", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Rock Hammer", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Wind Axe", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Tabar", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Thunder Kalinga Axe", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Neckchopper", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Cane", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Ocean Rod", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Water Rod", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Feather Staff", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Emerald Cane", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Wind Rod", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Shareeravadi", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Evil Wand", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Grenade", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Matchlock", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Straight Anchor", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Ranger Pistol", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Hand Pistol", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Jezail", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Fireball", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Heated Pata", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Pata", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Fish Tooth", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Gauntlet", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Tidal Wraps", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Rock Cutter", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mythril Baghnakhs", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Whirlwind Wraps", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Composite Bow", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mythril Bow", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Longbow", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Earth Bow", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Power Bow", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "War Bow", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Wrapped Bow", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Lyre of Lamia", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Nodachi", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mythril Katana", event: "None", character: "None", rarity: "R")

Summon.create(summontype: "Character", weapon: "Minotaur", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Twilight Devil", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Venom Lancer", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Walking Torch", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Angelie", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Crusher", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Jawfish", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Purgatorian", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Rivacuda", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Slime", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Swordshark", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Bonethorn", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Crawler", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Lumacie Griffin", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Mandrake", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Sleepyhead", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Belle", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Dragonflair", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Hornbird", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Rodfly", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Ghost Light", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Cave Bat", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Imp", event: "None", character: "None", rarity: "R")
Summon.create(summontype: "Character", weapon: "Skeleton", event: "None", character: "None", rarity: "R")

Summon.create(summontype: "Character", weapon: "Agni", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Athena (Summon)", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Michael", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Prometheus", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Satyr", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sethlans", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Shiva (Summon)", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sylph, Flutterspirit of Purity", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Twin Elements", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Zaoshen", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Bonito", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ca Ong", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Europa (Summon)", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gabriel", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Grani", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Kaguya", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Macula Marius (Summon)", event: "Summer", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Neptune", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Oceanus", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Poseidon, the Tide Father", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Snow White", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Varuna", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Ankusha", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Baal (Summon)", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Cybele", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gilgamesh", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Godsword Alexiel", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Gorilla", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Marduk, Battlefield Reaper", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Medusa (Summon)", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tezcatlipoca", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Titan", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Uriel", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Anat, for Love and War", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Demonbream", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Freyr", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Garuda", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Garula, Shining Hawk", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Grimnir (Summon)", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Hamsa", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Morrigna (Summon)", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Nezha", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Quetzalcoatl", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Raphael", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Rose Queen", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Setekh", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Siren", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Zephyrus", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Andramalech", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Aphrodite", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Apollo", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Grand Order", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Halluel and Malluel", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Hector", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Lucifer", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Magus, Triad of Wisdom", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Odin", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Thor", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Vortex Dragon", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Zeus", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Anubis", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Bahamut", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Cerberus, Hellhound Trifecta", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Dark Angel Olivia", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Hades", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Lich", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Nacht", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Sariel", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Satan", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Tsukuyomi", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Typhon", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Metatron", event: "None", character: "None", rarity: "SSR")
Summon.create(summontype: "Character", weapon: "Yggdrasil (Summer)", event: "Summer", character: "None", rarity: "SSR")
